channels:
- metadata:
    CHANNEL_ID: google_play
    MARKET_NAME: Google Play
  name: google_play
- metadata:
    CHANNEL_ID: huawei
    MARKET_NAME: Huawei AppGallery
  name: huawei
- metadata:
    CHANNEL_ID: xiaomi
    MARKET_NAME: Xiaomi MIUI Store
  name: xiaomi
- metadata:
    CHANNEL_ID: oppo
    MARKET_NAME: OPPO App Market
  name: oppo
- metadata:
    CHANNEL_ID: vivo
    MARKET_NAME: vivo App Store
  name: vivo
- metadata:
    CHANNEL_ID: yingyongbao
    MARKET_NAME: 应用宝
  name: 应用宝

output:
  directory: ./channels
  overwrite: true
version: 1.0